name: rewear
description: A community clothing exchange app

# Set the Dart SDK version
environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_database: ^10.4.3

  # Optional UI support
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
